# Generated by Django 5.2.4 on 2025-07-30 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_add_user', '增加用户')], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
