# Generated by Django 5.2.4 on 2025-07-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_add_user', '增加用户'), ('can_view_user', '查看用户'), ('can_change_user', '修改用户'), ('can_delete_user', '删除用户')], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
